authService:
  extends:
    file: ../docker-compose.yml
    service: authService
  environment:
    DB_URL: jdbc:postgresql://172.17.0.1:5432/authservice
    DB_USER: postgres
    DB_PASS: d4xZEoqO7HS5i2jpJL8vGQ==
    DB_DRIVER: org.postgresql.Driver
    HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    HIBERNATE_HBM2DDL_AUTO: update
    
